### PR TITLE
Implement `tox`

### PR DESCRIPTION
**Pull request by hrshdhgd**
- [x] Implement `tox` for linnting and code-formatting
 - [x] Anchored `jaro-winkler` at v2.0.0 since v2.0.1 install threw the following error:
    ```
    • Installing jaro-winkler (2.0.1): Failed

    ERROR: file:///Users/.../pypoetry/artifacts/.../jaro_winkler-2.0.1.linux-x86_64.tar.gz does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
    ```
 - [x] Add `click` as dependency in poetry.
 - [x] Add workflow for QC checks.

### CODE REVIEW

**Comment by justaddcoffee** [comment]
Looks good! Do you think we should provide a way for the user to specific the ontology, instead of hard-coding HPO?

**Comment by justaddcoffee** [comment]
>  I think so. Have the flexibility to provide an ontology and for the time being default it to HPO since that's our use case. Now we would need a list of ontologies supported though (right?) since the appropriate file needs to be downloaded first.

One way to do this would be to take an argument for the ontology containing the DAG (specifically a string argument containing the official OBO name of the ontology, e.g. 'HP' or 'MP')
https://obofoundry.org/ontology/hp.html
That way we wouldn't need a list of ontologies we support - we'd just support any ontology in kb-obo

**Comment by caufieldjh** [comment]
We cam just grab the [ontologies.yml](https://obofoundry.org/registry/ontologies.yml) from OBO Foundry to get ontology names - that's what KG-OBO uses anyway

**Comment by caufieldjh** [comment]
If `grape.datasets.kgobo` is doing the downloading then we don't really need the download/cache click options. I'll replace them with an arg for OBO graph to use

**Review by justaddcoffee — APPROVED** [review]

**Review by caufieldjh — APPROVED** [review]

**Pull request merged**
